version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: multi_tenant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  web:
    build: .
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      POSTGRES_DB: multi_tenant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A project worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A project beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

  frontend:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - '3001:3000'
    command: sh -c "npm install && npm start"
    depends_on:
      - web

volumes:
  pgdata:
