# Generated by Django 4.2.30 on 2026-09-04 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_document_owner_document_reviewed_at_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='risk',
            name='residual_impact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='residual_likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('mitigating', 'Mitigating'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='risk',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('archived', 'Archived')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.document')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive')], default='corrective', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('verified', 'Verified'), ('closed', 'Closed')], default='open', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='core.audit')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='core.risk')),
            ],
            options={
                'verbose_name': 'Corrective/Preventive Action',
                'ordering': ['-created_at'],
            },
        ),
    ]
