# Generated by Django 4.2.30 on 2026-09-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_risk_owner_risk_residual_impact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='risk',
            options={'ordering': ['-created_at']},
        ),
    ]
