# Generated by Django 4.2.30 on 2026-09-04 22:08

from django.db import migrations

# Belt-and-suspenders for "append-only": AuditLog.save()/.delete() already
# reject mutation at the ORM layer, but that's bypassable via bulk_update(),
# raw SQL, or the admin's bulk actions. This trigger makes UPDATE/DELETE on
# the table itself fail in Postgres, regardless of how it's attempted.
CREATE_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION core_auditlog_block_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'AuditLog entries are immutable (append-only) and cannot be % on row id=%', TG_OP, OLD.id;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER core_auditlog_no_update
BEFORE UPDATE ON core_auditlog
FOR EACH ROW EXECUTE FUNCTION core_auditlog_block_mutation();

CREATE TRIGGER core_auditlog_no_delete
BEFORE DELETE ON core_auditlog
FOR EACH ROW EXECUTE FUNCTION core_auditlog_block_mutation();
"""

DROP_TRIGGER_SQL = """
DROP TRIGGER IF EXISTS core_auditlog_no_update ON core_auditlog;
DROP TRIGGER IF EXISTS core_auditlog_no_delete ON core_auditlog;
DROP FUNCTION IF EXISTS core_auditlog_block_mutation();
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workflow_incident_evidence_control_auditlog_and_more'),
    ]

    operations = [
        migrations.RunSQL(sql=CREATE_TRIGGER_SQL, reverse_sql=DROP_TRIGGER_SQL),
    ]
