# Generated by Django 4.2.30 on 2026-09-04 23:43

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_auditlog_immutability_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(storage=core.storage.EncryptedFileSystemStorage(), upload_to='evidence/%Y/%m/'),
        ),
    ]
