# Generated by Django 4.2.30 on 2026-09-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['framework', 'identifier']},
        ),
        migrations.AddField(
            model_name='control',
            name='framework',
            field=models.CharField(choices=[('iso27001', 'ISO/IEC 27001:2022 Annex A'), ('soc2', 'SOC 2 (Common Criteria)'), ('custom', 'Custom')], default='iso27001', max_length=20),
        ),
        migrations.AlterField(
            model_name='control',
            name='identifier',
            field=models.CharField(help_text='e.g. A.5.1 (ISO 27001) or CC6.1 (SOC 2)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('framework', 'identifier')},
        ),
    ]
