# Generated by Django 4.2.30 on 2026-09-05 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('login_failed', 'Failed login'), ('signature_failed', 'Failed signature attempt')], max_length=20),
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printed_name', models.CharField(max_length=255)),
                ('meaning', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('reviewed', 'Reviewed'), ('authored', 'Authored')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('integrity_hash', models.CharField(editable=False, max_length=64)),
                ('signed_at', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
    ]
