# Generated by Django 4.2.30 on 2026-09-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_trainingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('login_failed', 'Failed login'), ('signature_failed', 'Failed signature attempt'), ('password_changed', 'Password changed')], max_length=20),
        ),
    ]
