# Generated by Django 4.2.30 on 2026-09-05 05:41

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(storage=core.storage.get_evidence_storage, upload_to='evidence/%Y/%m/'),
        ),
    ]
