# Generated by Django 4.2.30 on 2026-09-05 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remap_old_capa_statuses(apps, schema_editor):
    # CorrectiveAction.Status went from 4 stages (open/in_progress/
    # verified/closed) to 6 (open/investigation/action_planned/
    # action_implemented/verification/closed) — existing rows using the
    # old values would otherwise silently mismatch the new choices.
    CorrectiveAction = apps.get_model('core', 'CorrectiveAction')
    CorrectiveAction.objects.filter(status='in_progress').update(status='action_planned')
    CorrectiveAction.objects.filter(status='verified').update(status='verification')


def noop_reverse(apps, schema_editor):
    pass  # Old values aren't distinguishable enough to reverse-map meaningfully.


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_alter_evidence_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMatrixRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('workflow_step', 'Document approval (workflow step)'), ('corrective_action', 'Corrective/Preventive Action (close)')], max_length=30, unique=True)),
                ('required_role', models.CharField(help_text='Tenant role required: admin, auditor, or user', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='effectiveness_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(remap_old_capa_statuses, noop_reverse),
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigation', 'Investigation'), ('action_planned', 'Action planned'), ('action_implemented', 'Action implemented'), ('verification', 'Verification'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='meaning',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('reviewed', 'Reviewed'), ('authored', 'Authored'), ('verified', 'Verified')], max_length=20),
        ),
        migrations.CreateModel(
            name='Nonconformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('closed_no_action', 'Closed — no action'), ('escalated', 'Escalated to CAPA')], default='open', max_length=20)),
                ('closure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resulting_capa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.correctiveaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('data', 'Data'), ('facility', 'Facility'), ('service', 'Service')], default='hardware', max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='The specific thing this risk is about, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risks', to='core.asset'),
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('workflow_step', 'Document approval (workflow step)'), ('corrective_action', 'Corrective/Preventive Action (close)')], max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField()),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-approved_at'],
                'unique_together': {('entity_type', 'object_id')},
            },
        ),
    ]
