# Generated by Django 4.2.30 on 2026-09-05 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='classification',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Document ID'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_to_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
