# Generated by Django 4.2.30 on 2026-09-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_document_approver_document_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Asset ID'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under maintenance'), ('retired', 'Retired')], default='active', max_length=20),
        ),
    ]
