# Generated by Django 4.2.30 on 2026-09-05 13:43

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_asset_asset_id_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('policy', 'Policy'), ('sop', 'Standard Operating Procedure'), ('work_instruction', 'Work Instruction')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, storage=core.storage.get_evidence_storage, upload_to='documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='file',
            field=models.FileField(blank=True, storage=core.storage.get_evidence_storage, upload_to='documents/%Y/%m/'),
        ),
    ]
