# Generated by Django 4.2.30 on 2026-09-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_document_category_document_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('questions', models.JSONField(default=list, help_text='List of question strings.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('responded', 'Responded'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responses', models.JSONField(blank=True, default=list, help_text='List of {"question": ..., "answer": ...}.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='core.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
