# Generated by Django 4.2.30 on 2026-09-06 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_supplierquestionnaire_decided_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "ISO 27001 2026 Certification Audit"', max_length=255)),
                ('framework', models.CharField(blank=True, help_text='Leave blank for all frameworks.', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='e.g. auditor name/firm, for your own reference.')),
                ('access_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='The link stops working after this time, no exceptions.')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
