# Generated by Django 4.2.30 on 2026-09-06 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_auditoraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('aws', 'AWS')], max_length=20)),
                ('name', models.CharField(help_text='e.g. "Acme Corp GitHub Org"', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='disconnected', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_key', models.CharField(help_text='e.g. "branch_protection"', max_length=100)),
                ('label', models.CharField(help_text='Human-readable check name.', max_length=255)),
                ('passed', models.BooleanField()),
                ('detail', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_checks', to='core.control')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='core.integration')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
