# Generated by Django 4.2.30 on 2026-09-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_integration_integrationcheckresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='soa_justification',
            field=models.TextField(blank=True, help_text='Why this control is (or is not) applicable — shown on the generated Statement of Applicability.'),
        ),
    ]
