# Generated by Django 4.2.30 on 2026-09-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_control_soa_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='quiz_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='quiz_score',
            field=models.PositiveIntegerField(blank=True, help_text='Percent correct on the most recent quiz attempt.', null=True),
        ),
        migrations.AddField(
            model_name='trainingvideo',
            name='pass_percent',
            field=models.PositiveIntegerField(default=80, help_text='Minimum quiz score (%) required to pass.'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
                ('options', models.JSONField(default=list, help_text='List of answer choice strings.')),
                ('correct_index', models.PositiveIntegerField(help_text='Index into "options" for the correct answer.')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.trainingvideo')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
