# Generated by Django 4.2.30 on 2026-09-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_trainingrecord_quiz_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='framework',
            field=models.CharField(choices=[('iso27001', 'ISO/IEC 27001:2022 Annex A'), ('soc2', 'SOC 2 (Common Criteria)'), ('hipaa', 'HIPAA Security Rule'), ('gdpr', 'GDPR'), ('pci_dss', 'PCI DSS v4.0'), ('nist_csf', 'NIST Cybersecurity Framework 2.0'), ('custom', 'Custom')], default='iso27001', max_length=20),
        ),
    ]
