# Generated by Django 4.2.30 on 2026-09-06 21:34

import core.storage
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_document_archived_at_document_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, storage=core.storage.get_evidence_storage, upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt', 'csv', 'xls', 'xlsx', 'png', 'jpg', 'jpeg']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(storage=core.storage.get_evidence_storage, upload_to='evidence/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt', 'csv', 'xls', 'xlsx', 'png', 'jpg', 'jpeg']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='supplieragreement',
            name='file',
            field=models.FileField(blank=True, null=True, storage=core.storage.get_evidence_storage, upload_to='supplier-agreements/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'odt', 'txt', 'csv', 'xls', 'xlsx', 'png', 'jpg', 'jpeg']), core.validators.validate_document_size]),
        ),
        migrations.AlterField(
            model_name='trainingvideo',
            name='file',
            field=models.FileField(storage=core.storage.get_evidence_storage, upload_to='training-videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'm4v']), core.validators.validate_video_size]),
        ),
    ]
