# Generated by Django 4.2.30 on 2026-09-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_add_rls_to_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('team', 'Team'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
